---
- name: dnsmasq_config | configuring dnsmasq
  template:
    src: etc/dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq

- name: dnsmasq_config | creating dnsmasq_tftpboot_dir
  file:
    path: "{{ dnsmasq_tftpboot_dir }}"
    state: directory
  when: >
        (dnsmasq_enable_tftp is defined and dnsmasq_enable_tftp) or
        (dnsmasq_enable_dhcp_tftp is defined and dnsmasq_enable_dhcp_tftp)
