---
- name: redhat | installing dnsmasq
  yum:
    name: "dnsmasq"
    state: present
  when: ansible_distribution != "Fedora"

- name: redhat | installing dnsmasq
  dnf:
    name: "dnsmasq"
    state: present
  when: ansible_distribution == "Fedora"

- name: redhat | enabling on boot and started
  service:
    name: dnsmasq
    state: started
    enabled: yes
